#:kivy 1.10.1


<MainScreen>:
    GridLayout:
        cols:1

        Button:
            id: 'Stock Management Button'
            text: 'Stock'
            text_size: self.size
            valign: 'middle'
            halign: 'center'
            font_size: '25sp'

        Button:
            id: 'Analytics Button'
            text: 'Analytics'
            text_size: self.size
            valign: 'middle'
            halign: 'center'
            font_size: '25sp'

        
